run:
  deadline: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - structcheck
    - typecheck
    - deadcode
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - godot
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosec
    - interfacer
    - lll
    - misspell
    - nakedret
    - nestif
    - prealloc
    - whitespace
    - unconvert
    - unparam
    - stylecheck
