project_name: aenema

release:
  github:
    owner: sadqx
    name: aenema

checksum: { }

builds:
  - binary: aenema
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/aenema/main.go

archives:
  - id: binary
    format: binary
  - id: default
    format: tar.gz
